### ISSUE TITLE
render of "taxonomy" failed

### ISSUE THREAD

**Issue by simontree** [gethugothemes/techfeed-hugo#1]
Hey there, 
just tried to start the hugo server after downloading your zip and got this issue: 

hugo v0.87.0-B0C541E4+extended windows/amd64 BuildDate=2021-08-03T10:57:28Z VendorInfo=gohugoio
ERROR 2021/08/14 11:54:08 render of "taxonomy" failed: execute of template failed: template: _default/list.html:14:5: executing "_default/list.html" at <partial "head.html" .>: error calling partial: "A:\Hugo\sites\myblog\layouts\partials\head.html:25:18": execute of template failed: template: partials/head.html:25:18: executing "partials/head.html" at <add `assets/` $favicon>: error calling add: can't apply the operator to the values
ERROR 2021/08/14 11:54:08 render of "home" failed: execute of template failed: template: index.html:14:5: executing "index.html" at <partial "head.html" .>: error calling partial: "A:\Hugo\sites\myblog\layouts\partials\head.html:25:18": execute of template failed: template: partials/head.html:25:18: executing "partials/head.html" at <add `assets/` $favicon>: error calling add: can't apply the operator to the values
Error: Error building site: failed to render pages: render of "taxonomy" failed: execute of template failed: template: _default/list.html:14:5: executing "_default/list.html" at <partial "head.html" .>: error calling partial: "A:\Hugo\sites\myblog\layouts\partials\head.html:25:18": execute of template 
failed: template: partials/head.html:25:18: executing "partials/head.html" at <add `assets/` $favicon>: error calling add: can't apply the operator to the values     
Built in 43 ms
PS A:\Hugo\sites\myblog>

Do you have any idea how to handle this? 
I am using the current hugo version v0.87.0-B0C541E4+extended windows/amd64 
Best wishes

**Comment by somratpro** [comment]
Try this method https://github.com/gethugothemes/techfeed-hugo/wiki/installation

**Comment by simontree** [comment]
That's how I tried it already. Do you have any other ideas?

**Comment by tfsomrat** [comment]
This method works for me, not a single issue, make sure you are using hugo_extended v0.87.0

**Comment by hanmeran** [comment]
It works fine. thx.
