### ISSUE TITLE
OGP image not working

### ISSUE THREAD

**Issue by nacl30d** [gethugothemes/techfeed-hugo#5]
Hi there. Thank you for awesome template!
This template use image directory on `assets/images`, however, OGP image tries to resolve `static` and failed.
I thought his line should be `assets`?

https://github.com/gethugothemes/techfeed-hugo/blob/2c324c44ce160d43bf7f2189c98768e1b44f5759/layouts/partials/head.html#L43

**Comment by tfsomrat** [comment]
Hello @nacl30d 

Thanks for correcting us, It was a mistake. I fixed this. 

If you like this theme, a star to the repository would be incredible.
