### ISSUE TITLE
Inline Images in page not rendering 404 not found

### ISSUE THREAD

**Issue by bfrancom** [gethugothemes/techfeed-hugo#6]
Cloning and running vanilla repo doesn't render inline images.
eg) 
http://localhost:1313/techfeed/blog/post6/

```
Request URL: http://localhost:1313/assets/images/03.jpg
Request Method: GET
Status Code: 404 Not Found
Remote Address: 127.0.0.1:1313
Referrer Policy: strict-origin-when-cross-origin
Content-Length: 19
Content-Type: text/plain; charset=utf-8
Date: Sun, 07 Nov 2021 03:43:38 GMT
X-Content-Type-Options: nosniff
Accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Cookie: grafana_sess=97aa9355d2e94a73
Host: localhost:1313
Pragma: no-cache
Referer: http://localhost:1313/techfeed/blog/post6/
Sec-Fetch-Dest: image
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
Sec-GPC: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
```

**Comment by somratpro** [comment]
Hello @bfrancom 

You are requesting images in the `assets` folder. which will not be found on the rendered website. remove assets directory from your image call URL . ex: `http://localhost:1313/images/03.jpg`

**Comment by bfrancom** [comment]
@somratpro sorry, I tried, and still getting a 404.
Changed code in `post6.md` to:

```
![img](/images/03.jpg)
```

Have tried copying image in different directories:
```
exampleSite/images/03.jpg
exampleSite/assets/images/03.jpg
```

```
Request URL: http://localhost:1313/images/03.jpg
Request Method: GET
Status Code: 404 Not Found
```
Header images load fine. Just not inline images.  Thanks!

**Comment by somratpro** [comment]
Hello @bfrancom 

That's happening because assets image needs to be called with `resources.Get`. which is not possible without any shortcode. I'll suggest you put your images in the `static` folder. and don't mention the folder name (static) in your image call. 

or if you still want to put your images in the assets folder. you need to use a shortcode. see https://gohugo.io/content-management/shortcodes/
